### ISSUE TITLE
autostart_hummingbot_compose fails - No such file or directory... .password_verification

### ISSUE THREAD

**Issue by superclarkk** [hummingbot/deploy#20]
**Environment**
- Ubuntu 20.04
- Hummingbot deploy_examples (latest)

**Summary**
autostart_hummingbot_compose fails. Container exits after 10 seconds. Errors on docker attach, "FileNotFoundError: [Errno 2] No such file or directory: '/home/hummingbot/conf/.password_verification'" 

**Steps to reproduce**
- Follow [autostart_hummingbot_compose](https://github.com/hummingbot/deploy-examples/tree/main/autostart_hummingbot_compose)
- Copy the docker-compose.yml to a new directory. Edit it with password and strategy.
- Copy the `conf_pure_mm_SSWP-USDT.yml` strategy to the same directory
- Run `docker compose up -d`
- Observe, `✔ Container hummingbot-okx-sswp  Started `
- docker ps shows container stopped after about 10 seconds
- Run `sudo chmod -R a+rw ./hummingbot_files`
- Run `docker attach hummingbot-okx-sswp`. Returns, "You cannot attach to a stopped container, start it first"
- Run `docker start hummingbot-okx-sswp`
- Run `docker attach hummingbot-okx-sswp`, or `docker logs hummingbot-okx-sswp`. Returns errors below

**Errors**
```
Traceback (most recent call last):
  File "./bin/hummingbot_quickstart.py", line 155, in <module>
    main()
  File "./bin/hummingbot_quickstart.py", line 151, in main
    asyncio.get_event_loop().run_until_complete(quick_start(args, secrets_manager))
  File "/opt/conda/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./bin/hummingbot_quickstart.py", line 81, in quick_start
    if not Security.login(secrets_manager):
  File "/home/hummingbot/hummingbot/client/config/security.py", line 42, in login
    if not validate_password(secrets_manager):
  File "/home/hummingbot/hummingbot/client/config/config_crypt.py", line 72, in validate_password
    with open(PASSWORD_VERIFICATION_PATH, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hummingbot/conf/.password_verification'
```

**docker-compose.yml**
```
version: "3.9"
services:
  hummingbot:
    container_name: hummingbot-okx-sswp
    image: hummingbot/hummingbot:latest
    volumes:
      - "./hummingbot_files/conf:/home/hummingbot/conf"
      - "./hummingbot_files/conf/connectors:/home/hummingbot/conf/connectors"
      - "./hummingbot_files/conf/strategies:/home/hummingbot/conf/strategies"
      - "./hummingbot_files/logs:/home/hummingbot/logs"
      - "./hummingbot_files/data:/home/hummingbot/data"
      - "./hummingbot_files/scripts:/home/hummingbot/scripts"
      - "./hummingbot_files/certs:/home/hummingbot/certs"
    environment:
      - CONFIG_PASSWORD=aaa
      - CONFIG_FILE_NAME=conf_pure_mm_SSWP-USDT.yml
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
```

**Comment by fengtality** [comment]
@david-hummingbot Can you try to replicate what this user is seeing from the instructions? If more steps are needed, please suggest an update
