### ISSUE TITLE
Deploy - Unable to docker compose emqx

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/deploy#46]
When setting up source for testing [PR18](https://github.com/hummingbot/backend-api/pull/18), we have to use `docker compose. up emqx` for running the hummingbot-broker however it requires to manually add `.env` file which is created from `bash setup.sh`

![image](https://github.com/hummingbot/deploy/assets/73840223/d6a7ad99-4802-4983-97aa-820095268a51)

Workaround: Manually create `.env` file below:
```
CONFIG_PASSWORD=a
BOTS_PATH=insert-directory-of-deploy
```

Steps to reproduce:
1. Clone https://github.com/hummingbot/deploy
2. Run `docker compose up emqx -d`

**Comment by cardosofede** [comment]
this is not the expected way to use the project, that's why we have a setup.sh
