### ISSUE TITLE
Credentials - Create account accepts blank space 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/deploy#48]
### Describe the bug

When creating account, it accepts blank space 

![image](https://github.com/hummingbot/deploy/assets/73840223/c25bc5e8-7979-48de-a730-54dc42e6b87b)
![image](https://github.com/hummingbot/deploy/assets/73840223/5277d0f6-7bc3-4286-a48d-85111d8d1f03)
![image](https://github.com/hummingbot/deploy/assets/73840223/30b5db3f-570d-423c-ae67-415ae13dbeab)

### Steps to reproduce bug

1.  On `new account name`, press spacebar then create account

**Comment by cardosofede** [comment]
this is solved in the latest dashboard PR
