### ISSUE TITLE
`development` branch is out-of-date

### ISSUE THREAD

**Issue by intelliot** [hummingbot/deploy#59]
### Describe the bug

The `development` branch is out of date, resulting in confusion for new developers/users.

I recommend deleting the development branch and just using `main`. This simplifies branch management for developers. It is best to have only one branch to keep track of.

### Steps to reproduce bug

1. Clone `deploy`
2. Use `development` branch
3. Find that you are using an old version of the repo

**Comment by rapcmia** [comment]
Our team decided to proceed with adding updates to the main branch for now on both backend-api and dashboard.
