### ISSUE TITLE
After running Deploy, the connection with the host is disconnected

### ISSUE THREAD

**Issue by hack3rcon** [hummingbot/deploy#63]
### Describe the bug

Hello,
I am disconnect from the host when run the Deploy container and I have to connect to the server through the web panel and disconnect the containers.

Thank you.

### Steps to reproduce bug

```
# docker compose up
[+] Running 0/0
 ⠋ Network hummingbot_default  Creating
```
When I see the above message, my connection with the server is disconnected.

**Comment by hack3rcon** [comment]
Hello,
No idea?

Thanks.

**Comment by rapcmia** [comment]
Not able to reproduce.
